# Copyright 2016 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Builds the docker container for the e2e test.
FROM gcr.io/google_containers/kube-dnsmasq-amd64:1.4
MAINTAINER Bowei Du <bowei@google.com>

COPY bin/amd64/sidecar /sidecar
COPY bin/amd64/sidecar-e2e /sidecar-e2e
RUN apk update && apk add curl bind-tools

ENTRYPOINT ["/sidecar-e2e", "-mode", "test"]
