# Builds the docker container for the e2e test.
FROM gcr.io/google_containers/kube-dnsmasq-amd64:1.4
MAINTAINER Bowei Du <bowei@google.com>

COPY test/e2e/sidecar/docker-run-e2e.sh /docker-run-e2e.sh
COPY bin/amd64/sidecar /sidecar

RUN apk update && apk add curl bind-tools

ENTRYPOINT ["/bin/sh", "/docker-run-e2e.sh"]
