# Copyright 2016 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sudo: required
language: go
# trusty required for docker
# https://github.com/travis-ci/travis-ci/issues/5448
dist: trusty
go:
- 1.13.x

services:
- docker
install:
- mkdir -p ${GOPATH}/src/k8s.io
- ln -s `pwd` ${GOPATH}/src/k8s.io/dns
- go get -v github.com/onsi/ginkgo/ginkgo
- go get -v github.com/onsi/gomega
- go get -v -t ./...
- export PATH=$PATH:$HOME/gopath/bin

script:
- make build
- make test
- make all-containers
- bash test/e2e/sidecar/e2e.sh
- sudo -v
- ginkgo test/e2e
