sudo: required
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
dist: trusty
env:
- PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
services:
- docker
before_install:
- echo $encrypted_c3ffa94646c3_key | md5sum
- echo $encrypted_c3ffa94646c3_iv | md5sum
- openssl aes-256-cbc -K $encrypted_c3ffa94646c3_key -iv $encrypted_c3ffa94646c3_iv
  -in credentials.json.enc -out credentials.json -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
    curl https://sdk.cloud.google.com | bash;
  fi
- gcloud auth activate-service-account --key-file credentials.json
script:
- make build
- make test
- bash test/e2e/sidecar/e2e.sh
- make push
